rly_file = "Glasgow_Suburban.rly"
ttb_files = []
ssn_files = []
country_code = "GB"
name = ""
description = ""
display_name = "Glasgow Suburban"
author = "Kristian Zarębski"
contributors = [ "Kristian Zarebski",]
